/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KnowledgeVisualization: typeof import('./components/knowledge-visualization.vue')['default']
    MainChat: typeof import('./components/MainChat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeachingVisualization: typeof import('./components/teaching-visualization.vue')['default']
  }
}
